FROM confluentinc/cp-kafka-connect:7.5.3
RUN  confluent-hub install --no-prompt confluentinc/kafka-connect-json-schema-converter:7.5.3
RUN  confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.7.1
RUN  confluent-hub install --no-prompt confluentinc/kafka-connect-cassandra:2.0.5